'use strict'

module.exports = {
  USERNAME_IS_NOT_AVAILABLE: 'USERNAME_IS_NOT_AVAILABLE',
  WRONG_CREDENTIAL: 'WRONG_CREDENTIAL',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  LOGIN_ERROR: 'LOGIN_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_TOKEN: 'INVALID_TOKEN',
  NOT_EQUAL_PASSWORDS: 'NOT_EQUAL_PASSWORDS',
  EMAIL_NOT_VALID: 'Formato de email incorreto',
  OLINK_ERROR: 'OLINK_ERROR',
  OLINK_ERROR_INTERNAL: 'OLINK_ERROR_INTERNAL',
  OLINK_ERROR_BAD_REQUEST: 'OLINK_ERROR_BAD_REQUEST',
  OLINK_ERROR_AUTH: 'OLINK_ERROR_AUTH',
  ACCOUNT_TOKEN_NOT_FOUND: 'ACCOUNT_TOKEN_NOT_FOUND',
  UNVALIDATED_ACCOUNT: 'UNVALIDATED_ACCOUNT',
  WRONG_USER_OR_BANK: 'Não há usuário ou dados bancários',
  THERES_NO_AFFILIATE_ON_PRODUCT: 'Não há afiliados associados neste produto',
  AFFILIATE_NO_PRODUCT: 'O afiliado não é associado à esse produto'
}
